# Generated by Django 2.0.2 on 2018-03-05 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Temporary token',
                'verbose_name_plural': 'Temporary tokens',
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'datetime', 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
