# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='active_users',
            field=models.ManyToManyField(blank=True, related_name='active_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
