# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 13:47
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models
import stdimage.utils


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=stdimage.models.StdImageField(default='avatars/default_avatar.png', upload_to=stdimage.utils.UploadToUUID(path='avatars')),
        ),
    ]
