version: '3.4'

services:
  tu-django:
    build:
      context: server/
      dockerfile: /docker/Dockerfile-django
      args:
        - py_requirements=requirements/base.txt
    container_name: 'tu-django'
    labels:
      application: 'tu-django'
    # temporarily use dev entry point:
    command: bash docker/entrypoint.dev.sh
    env_file:
      - ./server/env/base.env
    expose:
      - '8001'
    depends_on:
      - tu-postgres
      - tu-redis
      - tu-celery

  tu-postgres:
    image: postgres:latest
    container_name: 'tu-postgres'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'tu'
    labels:
      application: 'tu-postgres'
    expose:
      - '5432'

  tu-redis:
    image: redis:latest
    container_name: 'tu-redis'
    labels:
      application: 'tu-redis'
    expose:
      - '6379'

  tu-nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile-nginx
    container_name: 'tu-nginx'
    labels:
      application: 'tu-nginx'
    volumes:
      - nginx-data-volume:/opt/tu/logs/nginx
      - static-volume:/opt/tu/static
    ports:
      - '80:80'
    command: bash scripts/entry-point.prod.sh
    depends_on:
      - tu-django
      - tu-react

  tu-react:
    build:
      context: ./client/
      dockerfile: docker/Dockerfile-react
    container_name: 'tu-react'
    labels:
      application: 'tu-react'
    volumes:
      - static-volume:/opt/tu/static/build
      # TODO: create a new dir, don't use build itself
    command: bash docker/entry-point.prod.sh

  tu-rabbitmq:
    image: rabbitmq:latest
    container_name: 'tu-rabbitmq'
    labels:
      application: 'tu-rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=pass
    expose:
      - '5672'
      - '15672'

  tu-celery:
    build:
      context: ./server/
      dockerfile: docker/Dockerfile-celery
    container_name: 'tu-celery'
    labels:
      application: 'tu-celery'
    env_file:
      - server/env/base.env
    command: bash docker/celery-entrypoint.sh
    depends_on:
      - tu-rabbitmq

volumes:
  db-data-volume:
  nginx-data-volume:
  static-volume:
