version: '3.4'

services:
  tu-django:
    command: bash docker/entrypoint.dev.sh
    env_file:
      - ./server/env/dev.env
    volumes:
      - ./server/:/opt/tu/django
    ports:
      - '8001:8001'

  tu-postgres:
    ports:
      - '5432:5432'

  tu-redis:
    ports:
      - '6379:6379'

  tu-nginx:
    volumes:
      - ./nginx/configurations/:/etc/nginx/configurations
    command: bash scripts/entry-point.dev.sh

  tu-react:
    expose:
      - '3000'
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/opt/tu/static
    command: bash -c "npm rebuild node-sass >/dev/null && npm start"

  tu-rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

  tu-celery:
    volumes:
      - ./server/:/opt/tu/celery
