# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-03 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueOfLegendsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('league', models.TextField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Master', 'Master'), ('Challenger', 'Challenger')], verbose_name="User's league")),
                ('division', models.TextField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], verbose_name="User's division")),
            ],
            options={
                'verbose_name': 'League of Legends account',
                'verbose_name_plural': 'League of Legends accounts',
            },
        ),
    ]
