# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 12:35
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueOfLegendsAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('league', models.PositiveIntegerField(choices=[(1, 'Bronze'), (2, 'Silver'), (3, 'Gold'), (4, 'Platinum'), (5, 'Diamond'), (6, 'Master'), (7, 'Challenger')], verbose_name="User's league")),
                ('division', models.PositiveIntegerField(choices=[(1, 'I'), (2, 'II'), (3, 'III'), (4, 'IV'), (5, 'V')], verbose_name="User's division")),
                ('server', models.PositiveIntegerField(choices=[(1, 'North America'), (2, 'EU West'), (3, 'EU Nordic & East'), (4, 'Latin America North'), (5, 'Latin America South'), (6, 'Brazil'), (7, 'Turkey'), (8, 'Russia'), (9, 'Oceania'), (10, 'Japan'), (11, 'Korea')], verbose_name="User's server")),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.UserProfile')),
            ],
            options={
                'verbose_name': 'League of Legends account',
                'verbose_name_plural': 'League of Legends accounts',
            },
        ),
        migrations.AlterUniqueTogether(
            name='leagueoflegendsaccount',
            unique_together=set([('username', 'server')]),
        ),
    ]
