FROM nginx:latest
RUN apt-get update && apt-get install -y inotify-tools

RUN rm /etc/nginx/conf.d/default.conf
COPY configurations/ /etc/nginx/configurations

WORKDIR /opt/tu/scripts
COPY '*.sh' ./
WORKDIR /opt/tu
