# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 14:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_room_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active_users',
            field=models.ManyToManyField(related_name='active_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
