# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_room_active_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='active_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='active_room', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name of the room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
