FROM python:3.6.2
WORKDIR /opt/tu/celery

# create unprivileged user
RUN adduser --disabled-password --gecos '' myuser

COPY requirements.txt requirements.txt

# install suitable requirements
RUN pip install -r requirements.txt

COPY . .
