FROM python:3.6.2
WORKDIR /opt/tu/celery

# create unprivileged user
RUN adduser --disabled-password --gecos '' myuser

COPY requirements/ requirements

# install suitable requirements
RUN pip install -r requirements/development.txt

COPY . .
