FROM python:3.6.2
WORKDIR /opt/tu/django

COPY requirements/ requirements

# install suitable requirements
ARG py_requirements
RUN pip install -r $py_requirements --src=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`

COPY . .
