FROM python:3.6.2
RUN mkdir -p /opt/tu/django
WORKDIR /opt/tu/django/
COPY . .
ARG py_requirements
RUN pip install -r $py_requirements --src=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
#RUN pip install -r requirements.txt --src=/usr/local/lib/python3.6/site-packages
