FROM python:3.6.2
WORKDIR /opt/tu/django

ENV LC_ALL=C.UTF-8 \
    LANG=C.UTF-8

# install suitable requirements
RUN pip install pipenv --src=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`

COPY . .
# later we can change to that but it is buggy https://github.com/pypa/pipenv/issues/1002
# RUN set -ex && pipenv install --dev --system
# for now we will use workaround and still use requirements.txt
RUN pip install -r requirements.txt --src=`python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`