FROM node:9.4.0

ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /opt/tu/static

# use only in prod mode to speed up dev build time
# node_modules are shared with host in dev mode
 COPY package.json ./
 RUN npm install --silent

COPY . .
